modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-or-later"

[[mods]]
modId="simplecoords"
version="${mod_version}"
displayName="SimpleCoords"
authors="Fayber"
description='''
A simple HUD displaying XYZ and subchunk coordinates.
'''

[[dependencies.simplecoords]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplecoords]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
